---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config
data:
    mydata: |-
      username: ramesh
      hometow: us

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      initContainers:
      - name: init-myapp
        image: gcr.io/mi-dev-env/ubuntu:latest
        command: ['sh', '-c', 'cp /var/config-volume/* /opt/shared-volume/']
        volumeMounts:
          - mountPath: /var/config-volume
            name: config-volume
          - mountPath: /opt/shared-volume
            name: shared-volume
      containers:
      - name: java-container-01
        image: gcr.io/mi-dev-env/java:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shared-volume
          mountPath: /mnt/shared-volume
        
      volumes:
      - name: shared-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: config  


